interface SchoolData {
    'ID INEP': string;
    CPF: string;
    'ALUNO(A)': string;
    'SITUAÇÃO': string;
    'DATA DE NASC.': string;
    'IDADE / MÊS': string;
    SEXO: string;
    CURSO: string;
    ETAPA: string;
    'SUB ETAPA (MULTISSERIADO)': string;
    TURNO: string;
    TURMA: string;
    'NOME DA TURMA': string;
    'BOLSA FAMÍLIA': string;
    NNE: string;
    PcD: string;
    'Tipo da Deficiência': string;
    'NOME DO PROFISSIONAL AE / PA': string;
    'TIPO TRANSPORTE': string;
    Rodoviário: string;
    Aquaviário: string;
    Capacidade: string;
    'FILIAÇÃO 1': string;
    'FILIAÇÃO 2': string;
    TIPO: string;
    'DATA MATRICULA': string;
    'DATA SITUAÇÃO': string;
    'ENVIAR CENSO': string;
    LOCALIZAÇÃO: string;
    BAIRRO: string;
    LOGRADOURO: string;
    NUMERO: string;
    COMPLEMENTO: string;
    'COR/RAÇA': string;
    TELEFONE: string;
    'OBSERVAÇÃO': string;
    'MATRÍCULA NOVA?': string;
    'NOME ESCOLA': string;
    'ETAPA GERAL': string;
  }
  